Project:
  name: 'FNO'
  database: 'GRF_15Hz'
  experiment: '25k'

data:
  PATH: "databases"
  PDE_type: "acoustic"
  process: 'GRF_15Hz'
  n_sample: 25000
  load_workers: 10
  frequency: 15
  
model:
  modes_list: [12,12,12,12]
  features: 36
  activ: "relu"

train:
  batchsize: 50
  epochs: 100
  lr: 0.001
  step_size: 40
  gamma: 0.5
  weight_decay: 0.00001

ckpt:
  PATH: "save_files"
  save_dir: 'acoustic/GRF_15Hz/relu/FNO'
  alias: 'FNO'