Project:
  name: 'FNO_residual'
  database: 'GRF_7Hz'
  experiment: '25k'

data:
  PATH: "databases"
  PDE_type: "acoustic"
  process: 'GRF_7Hz'
  n_sample: 25000
  load_workers: 10
  frequency: 7
   
model:
  modes_list: [12, 12, 12, 12]
  features: 36
  drop_path: 0.
  drop: 0.
  activ: "gelu"

train:
  batchsize: 50
  epochs: 100
  lr: 0.001
  step_size: 40
  gamma: 0.5
  weight_decay: 0.00001

ckpt:
  PATH: "save_files"
  save_dir: 'acoustic/GRF_7Hz/gelu/FNO_residual'
  alias: 'FNO_residual'